import type { Metadata } from "next";
import { Geist, Geist_Mono, Rajdhani, Merriweather } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { SoundProvider } from "@/contexts/SoundContext";
import { MoodProvider } from "@/contexts/MoodContext";
import { PlayerProvider } from "@/contexts/PlayerContext";
import GlassPlayer from "@/components/GlassPlayer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rajdhani = Rajdhani({
  variable: "--font-technical",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const merriweather = Merriweather({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rajdhani.variable} ${merriweather.variable} antialiased`}
      >
        <SoundProvider>
          <MoodProvider>
            <PlayerProvider token={process.env.NEXT_PUBLIC_SPOTIFY_ACCESS_TOKEN ?? ""}>
              {children}
              <GlassPlayer />
            </PlayerProvider>
            <SpeedInsights />
          </MoodProvider>
        </SoundProvider>
      </body>
    </html>
  );
}
